### ISSUE TITLE
API 설계 및 문서화

### ISSUE THREAD

**Issue by GREENOVER** [GREENOVER/ios-project-manager-server#2]
- [x] GitHub Wiki에 API Document 문서 공간 생성
- [x] API 설계
- [x] API 문서화
- [x] mock 데이터 생성
- [x] 클라이언트 파트 회의 후 API 문서 수정 및 결정

**Comment by hcooch2ch3** [comment]
### 클라이언트와 의논해볼 내용
#### URL
/things or /things/:id
#### state
String or Number
